# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Homebox Addon
version: "2.0.2"
slug: homebox
description: Homebox add-on
url: "https://github.com/jscarrott/homebox-addon/blob/main/example"
arch:
  # - armhf
  - armv7
  - aarch64
  - amd64
  # - i386
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/jscarrott/{arch}-addon-example"
ports:
  7745/tcp: 7745
